- name: Set kernel arg kvm.nx_huge_pages=off
  ansible.builtin.command: "rpm-ostree kargs --append-if-missing=kvm.nx_huge_pages=off"
  register: output
  changed_when: output.rc != 0
  failed_when: output.rc != 0
  when:
    - vulnerability_itlb_multihit
